---

# Create directory for hosts files
# Only when some hosts configuration provided
- name: Dnsmasq | Create directory for hosts files
  ansible.builtin.file:
    path: "{{ dnsmasq_dnsmasq_d_hosts_files_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: dnsmasq_dnsmasq_d_hosts_files
  tags:
    - config
    - hosts
    - dnsmasq
    - dnsmasq-config
    - dnsmasq-hosts

# Create hosts files in /etc/dnsmasq.d/
- name: Dnsmasq | Create hosts files
  ansible.builtin.template:
    src: etc/dnsmasq.d/hosts/hosts.j2
    dest: "{{ [dnsmasq_dnsmasq_d_hosts_files_dir, item.key] | path_join }}"
    owner: root
    group: root
    mode: "0644"
  ignore_errors: "{{ ansible_check_mode }}"
  with_dict: "{{ dnsmasq_dnsmasq_d_hosts_files }}"
  when:
    - dnsmasq_dnsmasq_d_hosts_files
    - item.value
    - item.value.get('state', 'present')  == 'present'
  notify: Dnsmasq reload
  tags:
    - config
    - hosts
    - dnsmasq
    - dnsmasq-config
    - dnsmasq-hosts

# Remove hosts files from /etc/dnsmasq.d/
- name: Dnsmasq | Remove hosts files
  ansible.builtin.file:
    path: "{{ [dnsmasq_dnsmasq_d_hosts_files_dir, item.key] | path_join }}"
    state: absent
  ignore_errors: "{{ ansible_check_mode }}"
  with_dict: "{{ dnsmasq_dnsmasq_d_hosts_files }}"
  loop_control:
    label: "key: {{ item.key }}, state: {{ item.value.get('state', 'unset') }}"
  when:
    - dnsmasq_dnsmasq_d_hosts_files
    - item.value
    - item.value.get('state', 'present') == 'absent'
  notify: Dnsmasq reload
  tags:
    - config
    - hosts
    - dnsmasq
    - dnsmasq-config
    - dnsmasq-hosts

# Create config that will enable use of generated hosts files via 'addn-hosts' parameter
- name: Dnsmasq | Create config with all hosts files referenced
  ansible.builtin.template:
    src: etc/dnsmasq.d/hosts.conf.j2
    dest: "{{ dnsmasq_dnsmasq_d_hosts_config_filename }}"
    owner: root
    group: root
    mode: "0644"
  when:
    - dnsmasq_dnsmasq_d_hosts_files
    - dnsmasq_dnsmasq_d_hosts_config_create
  notify: Dnsmasq restart
  tags:
    - config
    - hosts
    - dnsmasq
    - dnsmasq-config
    - dnsmasq-hosts
