---

- name: Dnsmasq restart
  ansible.builtin.service:
    name: "{{ dnsmasq_service_name }}"
    state: restarted
  ignore_errors: "{{ ansible_check_mode }}"
  when: dnsmasq_service_manage | bool

- name: Dnsmasq reload
  ansible.builtin.service:
    name: "{{ dnsmasq_service_name }}"
    state: reloaded
  ignore_errors: "{{ ansible_check_mode }}"
  when: dnsmasq_service_manage | bool
